CREATE DATABASE blog TEMPLATE template0;
\c blog;

BEGIN;
CREATE SCHEMA IF NOT EXISTS pgTAP;
CREATE EXTENSION IF NOT EXISTS pgtap SCHEMA pgTAP;
CREATE USER blogdba WITH PASSWORD 'SCRAM-SHA-256$4096:QQ59l2EzY+2r4L8KCNkfMA==$XbnSqA45KtuT6PxB9YOY864WJf0475cCToN7/43GbTw=:AQrPHnFvdzqRdFItOGT+dTVwn1rWqVZGDRBsvJ2mwAE=';
CREATE USER blogdbu WITH PASSWORD 'SCRAM-SHA-256$4096:pm3YdXHt7YvplGyg9+6OXA==$HTnA5evA83isBlB3q7hk1TuaCQdJ3RpV3PrrYYgEfOU=:qSBujALhl9I3lZ3tqw0mowHlFq4WSjwxyEYVh9dM/oI=';

REVOKE CONNECT,CREATE,TEMPORARY ON DATABASE blog FROM public;
GRANT CONNECT,CREATE,TEMPORARY ON DATABASE blog TO blogdba;
GRANT CONNECT,TEMPORARY ON DATABASE blog TO blogdbu;

REVOKE CREATE,USAGE ON SCHEMA public FROM public;
GRANT CREATE,USAGE ON SCHEMA public TO blogdba;
GRANT USAGE ON SCHEMA public to blogdbu;

COMMIT;